from pathlib import Path


# MACROS
ENV_FILE_PATH = Path(__file__).parent
ENV_DEBUG_LEVEL_PATH = ENV_FILE_PATH / "DEBUG_LEVEL.env"
ENV_AIR_TABLE_PATH = ENV_FILE_PATH / "AIRTABLE_ENV.env"

# log levels
MAIN_DEBUG_LEVEL = "MAIN_LOG_LEVEL"
GOOGLE_API_LOG_LEVEL = "GOOGLE_API_LOG_LEVEL"
AIR_TABLE_LOG_LEVEL = "AIR_TABLE_LOG_LEVEL"
CHART_JS_TABLE_LOG_LEVEL = "CHART_JS_TABLE_LOG_LEVEL"

# airTable
AIR_TABLE_ID_DATA = "AIR_TABLE_ID"
AIR_TABLE_API_KEY_DATA = "AIR_TABLE_API_KEY"


